name: Meshery GitOps Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meshery-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Layer5 Meshery Action
        uses: layer5io/meshery-action@master
        continue-on-error: true
        with:
          provider_token: ${{ secrets.MESHERY_TOKEN }}
